<?php $print = $error ?? $data ?? 'Ошибка'; ?>

<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
    <base href=""/>
    <title>Teashka Bot</title>
    <meta charset="utf-8"/>

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#12121200">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

    <!-- About App -->
    <meta name="language" content="RU"/>
    <meta name="robots" content="noindex,nofollow"/>
    <meta name="title" content="Zorin Projects S.P."/>
    <meta name="description" content="Creative Lab for Internet Development and Research"/>
    <meta name="keywords" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <!-- Apple Meta Tags -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-touch-fullscreen" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no"/>

    <!-- About Creator App -->
    <meta name="owner" content="Ivan Zorin"/>
    <meta name="designer" content="designer@zorin.space"/>
    <meta name="author" content="Ivan Zorin, ivan@zorin.space"/>
    <meta name="copyright" content="Zorin Projects S.P."/>
    <meta name="reply-to" content="support@zorin.space"/>

    <!-- About System -->
    <meta name="generator" content="Triangle Framework"/>
    <meta name="server" content="Localzet Server"/>

    <!-- Cache&Content -->
    <meta http-equiv="Expires" content="60"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- SEO -->
    <link rel="icon" type="image/svg+xml" href="https://cdn.localzet.com/media/localzet.svg"/>
    <link rel="shortcut icon" type="image/svg+xml" href="https://cdn.localzet.com/media/localzet.svg"/>

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900"/>

    <style>
        body {
            background-color: #000;
            font-family: Nunito, monospace;
            font-weight: 600;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            overflow: hidden;
        }

        main {
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
            max-height: 90vh;
            overflow: auto;
            height: fit-content;
        }


        main img {
            display: block;
            -webkit-user-select: none;
            transition: background-color 300ms;

            max-width: 300px;
            width: 300px;
        }

        main h1 {
            margin: 0;
            color: #FF3767;
            font-size: 3rem;
        }

        main span {
            color: #FF7E00;
            font-size: 1rem;
            margin-top: -38px;
        }

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            margin-bottom: 5px;
        }

        footer nav {
            text-align: center;
        }

        footer nav a {
            text-decoration: none !important;
            color: #6e7681;
            margin: 0 3px;
            display: inline-block;
        }

        footer nav a b {
            color: #7b69c8;
        }

        hr {
            border-color: #7b69c8;
            border-radius: 50%;
            width: 100%;
        }

        details[open] {
            text-align: start;
            width: 90vw;
        }

        @media (max-width: 600px) {
            main {
                margin-top: calc(-50px + -12rem);
            }

            main img {
                margin: auto 5%;
                width: 80%;
                height: auto;
            }
        }
    </style>
</head>

<body>
<main>
    <img src="https://my.e.donstu.ru/t/assets/media/TDSTU-Security.svg" alt="Zorin Projects S.P.">
    <h1><?= is_string($print) ? $print : ($print['error'] ?? "~Неизвестный формат~") ?></h1>
    <?php if (@$traces) : ?>
        <details>
            <?= $traces ?>
        </details>
    <?php endif; ?>
</main>
<footer>
    <hr/>
    <nav>
        <a target="_blank" href="https://t.me/dstu_devs">Created by <b>T-Developers</b></a>
        <a target="_blank" href="https://github.com/localzet/server">Powered by <b>Localzet Server</b></a>
    </nav>
</footer>
</body>

</html>