<?php

/**
 * @package     Triangle Web
 * @link        https://github.com/Triangle-org
 *
 * @copyright   2018-2023 Localzet Group
 * @license     https://mit-license.org MIT
 */

use localzet\Server;

?>

<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
    <base href=""/>
    <title>Triangle Web</title>
    <meta charset="utf-8"/>

    <!-- About App -->
    <meta name="language" content="RU"/>
    <meta name="robots" content="noindex,nofollow"/>

    <!-- About System -->
    <meta name="generator" content="Triangle Framework"/>
    <meta name="server" version="Localzet Server <?= Server::getVersion() ?? '' ?>"/>

    <!-- Cache&Content -->
    <meta http-equiv="Expires" content="60"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <!-- SEO -->
    <link rel="shortcut icon" type="image/svg+xml" href="//cdn.localzet.com/media/localzet.svg"/>

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#12121200">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900"/>

    <style>
        html {
            /* height: 100%; */
        }

        body {
            /* background-color: #0e0e0e; */
            background-color: #000;

            font-family: Nunito, monospace;
            font-weight: 600;

            text-align: center;
            text-decoration: none !important;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            overflow: hidden;
        }

        /*center {*/
        /*    height: 90vh;*/
        /*    overflow: auto;*/
        /*}*/

        h1 {
            font-size: 1.6rem;
            word-wrap: break-word;
            width: 90vw;
            /*height: 90vh;*/
            /*overflow-y: scroll;*/
            /*display: inline-block;*/
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            margin-bottom: 5px;
        }

        .footer a {
            text-decoration: none;
            color: #6e7681;
            margin: 0 3px;
            /* white-space: nowrap; */
            display: inline-block;
        }

        .footer a b {
            color: #50cd89;
        }

        img {
            display: block;
            -webkit-user-select: none;
            /* margin: calc(48vh - 80px) calc(50vw - 400px); */
            transition: background-color 300ms;

            max-width: 800px;

            width: 800px;
            /* height: 160px; */
        }

        hr {
            border-color: #50cd89;
            border-radius: 50%;
            width: 100%;
        }

        /* Медиа-запрос для экранов меньше 800px */
        @media (max-width: 900px) {
            img {
                margin: auto 5%;
                width: 90%;
                height: auto;
            }
        }
    </style>
</head>

<body>
<center>
    <h1>
        <?php $print = $error ?? $data ?? 'Ошибка'; ?>
        <?= is_string($print) ? $print : print_r($print, true) ?>
    </h1>
</center>
<div class="footer">
    <hr>
    <a href="https://github.com/localzet/server">Powered by <b>Localzet
            Server <?= @Server::getVersion() ?? '' ?></b></a>
</div>
</body>

</html>