#!/usr/bin/env php
<?php

/**
 * @package     Triangle Engine (FrameX Project)
 * @link        https://github.com/localzet/FrameX      FrameX Project v1-2
 * @link        https://github.com/Triangle-org/Engine  Triangle Engine v2+
 *
 * @author      Ivan Zorin <creator@localzet.com>
 * @copyright   Copyright (c) 2018-2023 Localzet Group
 * @license     https://www.gnu.org/licenses/agpl AGPL-3.0 license
 *
 *              This program is free software: you can redistribute it and/or modify
 *              it under the terms of the GNU Affero General Public License as
 *              published by the Free Software Foundation, either version 3 of the
 *              License, or (at your option) any later version.
 *
 *              This program is distributed in the hope that it will be useful,
 *              but WITHOUT ANY WARRANTY; without even the implied warranty of
 *              MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *              GNU Affero General Public License for more details.
 *
 *              You should have received a copy of the GNU Affero General Public License
 *              along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use Triangle\Engine\Config;
use Triangle\Engine\Console\Application;
use Triangle\Engine\Console\Command\Command;

require_once __DIR__ . '/vendor/autoload.php';

if (!in_array($argv[1] ?? '', ['start', 'restart', 'stop', 'status', 'reload', 'connections'])) {
    require_once __DIR__ . '/support/bootstrap.php';
} else {
    Config::load(config_path(), ['route', 'container']);
}

$cli = new Application();
$cli->setName('Localzet Master CLI');
if (is_dir($command_path = app_path() . '/command')) {
    $dir_iterator = new RecursiveDirectoryIterator($command_path);
    $iterator = new RecursiveIteratorIterator($dir_iterator);
    foreach ($iterator as $file) {
        if (is_dir($file)) {
            continue;
        }
        $class_name = 'app\\command\\' . basename($file, '.php');
        if (!is_a($class_name, Command::class, true)) {
            continue;
        }
        $cli->add(new $class_name);
    }
}

foreach (config('plugin', []) as $firm => $projects) {
    if (config("plugin.$firm.app", false)) continue;
    foreach ($projects as $name => $project) {
        foreach ($project['command'] ?? [] as $command) {
            $cli->add(new $command);
        }
    }
}

try {
    $cli->run();
} catch (Exception $e) {
}
