<?php

/**
 * @package     Triangle Web
 * @link        https://github.com/Triangle-org
 *
 * @copyright   2018-2023 Localzet Group
 * @license     https://mit-license.org MIT
 */

use localzet\Server\Server;

?>
<!DOCTYPE html>

<html lang="ru" prefix="og: http://ogp.me/ns#">

<head>
    <base href="" />
    <title><?= $name ?></title>
    <meta charset="utf-8" />

    <!-- About App -->
    <meta name="language" content="RU" />
    <meta name="robots" content="noindex,nofollow" />
    <meta name="title" content="<?= $name ?>" />
    <meta name="viewport" content="<?= $viewport ?>" />

    <!-- About Creator App -->
    <meta name="owner" content="<?= $owner ?>" />
    <meta name="designer" content="<?= $designer ?>" />
    <meta name="author" content="<?= $author ?>" />
    <meta name="copyright" content="<?= $copyright ?>" />
    <meta name="reply-to" content="<?= $reply_to ?>" />

    <!-- About System -->
    <meta name="project" content="<?= $name ?>" domain="<?= config('app.domain', '!notSET!') ?>" assets="<?= config('app.src', '!notSET!') ?>" />
    <meta name="generator" content="Triangle Framework" debug="<?= config('app.debug', '!notSET!') ?>" />
    <meta name="server" version="<?= config('app.headers.server', 'Localzet Server') ?>" />

    <!-- Cache&Content -->
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">

    <!-- Apple Meta Tags -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />

    <!-- SEO -->
    <link rel="icon" type="image/svg+xml" href="<?= $logo ?>" />
    <link rel="shortcut icon" type="image/svg+xml" href="<?= $logo ?>" />

    <meta name="color-scheme" content="dark light">
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#00000000">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff00">

    <!-- Fonts -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Nunito:100,200,300,400,500,600,700,800,900" />
    <style>
        * {
            font-family: 'Nunito';
        }
    </style>
</head>

<body>
    <br />
    <center>
        <h1>
            <?php $print = $error ?? $data; ?>
            <?= is_string($print) ? $print : print_r($print, true) ?>
        </h1>
    </center>
    <hr />
    <center>
        <a href="https://github.com/localzet/server" style="text-decoration: auto;">Localzet Server <?= Server::VERSION ?></a>
    </center>
</body>

</html>